// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-NCFVrlTy_unlHZCjoiicCpCh56xxno',
    appId: '1:160164517005:web:cf8794280c068c0f8afec4',
    messagingSenderId: '160164517005',
    projectId: 'fixture2022-wcq',
    authDomain: 'fixture2022-wcq.firebaseapp.com',
    databaseURL: 'https://fixture2022-wcq-default-rtdb.firebaseio.com',
    storageBucket: 'fixture2022-wcq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVhHVipl1JFLhVhVRQNDZjAHEgcxoQJ8',
    appId: '1:160164517005:android:0fdc9170dddd5b4f8afec4',
    messagingSenderId: '160164517005',
    projectId: 'fixture2022-wcq',
    databaseURL: 'https://fixture2022-wcq-default-rtdb.firebaseio.com',
    storageBucket: 'fixture2022-wcq.appspot.com',
  );
}
